name: medicare_web
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  dart_jsonwebtoken: ^2.8.0
  internet_connection_checker: ^1.0.0+1
  appwrite: 12.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  gap: ^3.0.1
  speech_to_text: ^6.6.1
  google_generative_ai: ^0.2.2
  file_picker: ^8.0.0+1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
